### ISSUE TITLE
RM ANOVA: HF-corrected p-value not equal to uncorrected p-value when HFe > 1

### ISSUE THREAD

**Issue by borisma** [jamovi/jmv#106]
Hi there,
In cases where the HF-epsilon gets > 1  it is set to 1 as in `spherTest` of `anovaRM()`. However, in `spherCorr` in this case the dfs are not set to the uncorrected dfs as they should be, but become greater than the uncorrected ones (because df-computation is based on the "raw" HF-epsilon). This results in incorrect (too low) p-value for the HF-correction in this case.

Thanks for all your work!!

Boris

**Comment by jonathon-love** [comment]
hi boris! (ravi will take care of this, but just wanted to say hi! :)

**Comment by borisma** [comment]
Hi there! I just tried out the new version and it seems that although the dfs, Mean Squares,  F- and p-Values are now correct for the RM effects (when HF epsilon > 1), but the dfs and Mean Square for the Residual component is still based on the "wrong" (>1) HF epsilon value. 
Obviously F- and p-values of effects are now computed on the uncorrected version (since it does not differ if HF epsilon is set to 1). Still the residual dfs and Mean Square should also be corrected.
Clear what I mean? Cheers from Bern!

**Comment by raviselker** [comment]
Thanks for checking this and reporting it (again). This will be fixed in the next release (at least, I hope it will be :stuck_out_tongue_winking_eye:).

**Comment by borisma** [comment]
Hi! Another thing: regarding Post-hoc tests in (all kinds of ) ANOVAs : `postHoc = "factor_1",  postHocCorr = c("none", "tukey", "bonf")`. There is a problem in the output with the table display of the corrected p-values. The subscripts `Tukey`  etc. in the table header are not rendered properly. This also leads to a breakdown when compiling output with `bookdown`. Thanks!

**Comment by jonathon-love** [comment]
hi @borisma,

i've committed a fix to `jmvcore` which should fix formatting issues in column headings with these corrections. unfortunately, CRAN doesn't like us resubmitting packages more than once a month, so i can't push to CRAN for another few weeks.

cheers

jonathon

**Comment by borisma** [comment]
Thanks!
