### ISSUE TITLE
Phi-coefficient producing NaN for contingency table

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#137]
Hi,

I am using the jmv package (0.8.1.11) to run contingency table analysis but having trouble to get the phi coefficient as effect size.

Code: `jmv::contTables(data, rows = 'rows', cols = 'columns', phiCra = TRUE)`

![image](https://user-images.githubusercontent.com/11330453/34306559-d6497d58-e711-11e7-9271-bda5a588feee.png)

Here is the data, in case you want to reproduce the error.

rows | columns
-- | --
compensation | punishment
control | compensation
compensation | compensation
control | compensation
punishment | compensation
control | punishment
punishment | compensation
compensation | compensation
control | compensation
punishment | punishment
compensation | compensation
punishment | punishment
compensation | compensation
control | compensation
punishment | punishment
compensation | compensation
control | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | punishment
control | punishment
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | punishment
compensation | punishment
control | compensation
compensation | compensation
punishment | punishment
control | compensation
compensation | compensation
control | punishment
punishment | punishment
punishment | compensation
control | punishment
compensation | punishment
control | punishment
compensation | punishment
punishment | punishment
control | compensation
compensation | punishment
punishment | compensation
punishment | punishment
control | compensation
compensation | compensation
compensation | compensation
control | punishment
punishment | punishment
control | punishment
punishment | compensation
compensation | compensation
compensation | compensation
punishment | compensation
control | compensation
control | compensation
compensation | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | compensation
punishment | compensation
compensation | compensation
control | compensation
control | compensation
punishment | compensation
compensation | compensation
control | punishment
punishment | punishment
control | compensation
compensation | compensation
punishment | compensation
control | compensation
compensation | punishment
punishment | compensation
control | compensation
punishment | punishment
compensation | punishment
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | compensation
control | punishment
punishment | punishment
compensation | compensation
control | compensation
punishment | punishment
control | compensation
compensation | punishment
compensation | punishment
control | compensation
punishment | punishment
control | compensation
compensation | punishment
punishment | compensation
control | punishment
punishment | compensation
compensation | punishment
punishment | compensation
compensation | compensation
control | compensation
control | punishment
punishment | punishment
compensation | compensation
control | punishment
punishment | punishment
compensation | compensation
punishment | punishment
control | compensation
compensation | punishment
punishment | punishment
compensation | punishment
punishment | compensation
control | punishment
compensation | compensation
control | compensation
punishment | compensation
compensation | punishment
punishment | compensation
control | compensation
punishment | compensation
control | punishment
compensation | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | compensation
control | punishment
compensation | compensation
control | compensation
punishment | punishment
compensation | compensation
control | punishment
compensation | punishment
punishment | compensation
control | punishment
punishment | compensation
compensation | compensation
control | compensation
control | punishment
compensation | compensation
punishment | punishment
compensation | punishment
control | punishment
punishment | compensation
punishment | compensation
control | compensation
compensation | compensation
control | punishment
compensation | compensation
punishment | compensation
control | compensation
punishment | punishment
compensation | punishment
control | compensation
punishment | compensation
control | punishment
punishment | punishment
compensation | punishment
punishment | compensation
control | compensation
compensation | compensation
compensation | punishment
punishment | compensation
control | compensation
compensation | compensation
control | compensation
compensation | compensation
control | punishment
punishment | compensation
control | compensation
punishment | punishment
compensation | compensation
compensation | compensation
punishment | punishment
control | compensation
punishment | compensation
compensation | punishment
control | punishment
compensation | punishment
control | compensation
punishment | punishment
control | compensation
compensation | compensation
punishment | punishment
compensation | compensation
control | compensation
control | punishment
punishment | compensation
compensation | compensation
punishment | punishment
compensation | compensation
control | compensation
compensation | punishment
punishment | punishment
control | compensation
compensation | punishment
punishment | punishment
control | compensation
compensation | compensation
punishment | compensation
control | punishment
compensation | punishment
punishment | compensation
control | compensation
compensation | compensation
control | punishment
punishment | punishment
control | compensation
punishment | punishment
compensation | compensation
control | punishment
compensation | punishment
punishment | punishment
compensation | compensation
punishment | compensation
control | punishment
control | punishment
compensation | compensation
compensation | compensation
punishment | punishment
control | compensation
compensation | compensation
control | punishment
punishment | punishment
punishment | compensation
compensation | compensation
control | compensation
control | compensation
compensation | compensation
punishment | punishment
compensation | punishment
punishment | compensation
control | compensation
punishment | compensation
compensation | compensation
control | punishment
punishment | punishment
control | punishment
compensation | punishment
control | compensation
compensation | punishment
punishment | compensation
control | compensation
punishment | punishment
compensation | compensation
control | compensation
punishment | compensation
compensation | compensation
compensation | punishment
control | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | punishment
compensation | compensation
punishment | punishment
control | punishment
control | compensation
compensation | punishment
punishment | compensation
control | punishment
compensation | compensation
punishment | compensation
compensation | punishment
control | punishment
punishment | punishment
punishment | punishment
compensation | punishment
control | compensation
punishment | punishment
compensation | compensation
control | compensation
compensation | compensation
punishment | compensation
control | punishment
compensation | compensation
control | punishment
punishment | compensation
control | compensation
punishment | compensation
compensation | compensation
punishment | punishment
control | compensation
compensation | compensation
punishment | compensation
compensation | punishment
control | compensation
control | punishment
compensation | compensation
punishment | punishment
punishment | punishment
compensation | compensation
control | punishment
control | compensation
compensation | punishment
punishment | compensation
control | compensation
compensation | punishment
punishment | punishment
control | punishment
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | compensation
control | punishment
compensation | compensation
control | compensation
punishment | punishment
control | compensation
compensation | compensation
punishment | punishment
punishment | compensation
compensation | compensation
control | compensation
control | compensation
compensation | compensation
punishment | punishment
punishment | punishment
compensation | compensation
control | compensation
compensation | compensation
control | compensation
punishment | punishment
compensation | compensation
punishment | punishment
control | compensation
control | punishment
compensation | compensation
punishment | compensation
control | punishment
compensation | punishment
punishment | compensation
punishment | compensation
control | punishment
compensation | compensation
punishment | punishment
control | compensation
compensation | punishment
compensation | compensation
control | compensation
punishment | compensation
compensation | punishment
punishment | compensation
control | punishment
control | compensation
compensation | compensation
punishment | punishment
punishment | punishment
control | compensation
punishment | punishment
compensation | punishment
control | compensation
compensation | compensation
punishment | punishment
control | compensation
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
control | compensation
punishment | compensation
control | punishment
punishment | compensation
compensation | punishment
control | compensation
punishment | compensation
compensation | punishment
punishment | compensation
compensation | compensation
control | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | punishment
control | punishment
compensation | compensation
control | punishment
compensation | compensation
punishment | compensation
compensation | punishment
control | compensation
punishment | punishment
control | compensation
compensation | punishment
punishment | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | punishment
control | punishment
compensation | compensation
control | compensation
punishment | compensation
punishment | compensation
control | compensation
compensation | punishment
compensation | punishment
compensation | punishment
compensation | compensation
punishment | compensation
control | compensation
control | punishment
punishment | compensation
punishment | punishment
control | compensation
compensation | compensation
compensation | punishment
punishment | punishment
control | compensation
compensation | compensation
punishment | punishment
control | punishment
control | compensation
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | punishment
control | compensation
punishment | compensation
compensation | compensation
control | punishment
compensation | compensation
punishment | punishment
punishment | punishment
compensation | compensation
control | punishment
control | compensation
punishment | compensation
compensation | compensation
compensation | punishment
control | punishment
punishment | punishment
control | compensation
compensation | compensation
punishment | compensation
punishment | punishment
compensation | compensation
control | punishment
punishment | compensation
compensation | compensation
control | compensation
compensation | punishment
control | punishment
punishment | punishment
control | punishment
punishment | compensation
compensation | compensation
control | punishment
compensation | compensation
punishment | compensation
control | punishment
punishment | compensation
compensation | punishment
control | compensation
punishment | punishment
compensation | compensation
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | compensation
control | compensation
control | punishment
compensation | compensation
punishment | punishment
compensation | compensation
punishment | punishment
control | punishment
control | punishment
punishment | punishment
compensation | compensation
compensation | punishment
control | compensation
punishment | punishment
punishment | compensation
compensation | compensation
control | punishment
punishment | punishment
control | punishment
compensation | punishment
control | compensation
punishment | compensation
punishment | compensation
compensation | punishment
control | compensation
compensation | compensation
control | compensation
punishment | punishment
punishment | punishment
control | punishment
compensation | compensation
control | compensation
compensation | compensation
punishment | compensation
compensation | compensation
punishment | punishment
control | compensation
punishment | compensation
compensation | compensation
compensation | punishment
control | compensation
punishment | compensation
control | punishment
compensation | punishment
punishment | punishment
punishment | punishment
control | punishment
compensation | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | compensation
compensation | compensation
control | compensation
control | punishment
compensation | punishment
punishment | punishment
compensation | compensation
control | punishment
punishment | compensation
compensation | punishment
punishment | punishment
control | punishment
compensation | punishment
punishment | punishment
control | compensation
control | compensation
compensation | punishment
punishment | compensation
compensation | compensation
control | punishment
punishment | punishment
compensation | punishment
control | compensation
punishment | compensation
compensation | compensation
control | compensation
punishment | punishment
punishment | compensation
control | compensation
compensation | compensation
control | punishment
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | compensation
control | compensation
compensation | compensation
punishment | punishment
compensation | punishment
punishment | punishment
control | punishment
control | compensation
compensation | punishment
punishment | punishment
compensation | punishment
punishment | compensation
control | compensation
punishment | punishment
control | punishment
compensation | compensation
compensation | punishment
punishment | compensation
compensation | compensation
punishment | punishment
control | compensation
control | compensation
punishment | punishment
compensation | punishment
control | punishment
punishment | punishment
compensation | compensation
punishment | punishment
control | compensation
compensation | punishment
control | compensation
compensation | compensation
punishment | compensation
compensation | punishment
punishment | punishment
control | compensation
control | compensation

**Comment by raviselker** [comment]
Hi,
Phi is only defined for 2x2 tables (and yours is 3x2). We should probably add a footnote to the results to make people aware of this. Thanks!

**Comment by IndrajeetPatil** [comment]
Ah, completely forgot about that! 
Cool, I'll use Cramer's _V_ instead. But, yes, a warning will be helpful, lest a non-attentive user thinks that this is a bug.
