### ISSUE TITLE
A few issues with binary logistic regression

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#145]
A few errors in binary logistic regression:

(i already sent you this one):
[blre.omv.zip](https://github.com/jamovi/jmv/files/1694363/blre.omv.zip)

when you have no variables in blocks:
[blre2.omv.zip](https://github.com/jamovi/jmv/files/1694369/blre2.omv.zip)

**Comment by jonathon-love** [comment]
hey @dropmann,

this second file looks like your issue:

https://youtu.be/3KsP1IoIDag

**Comment by dropmann** [comment]
This issue is now fixed. Sorry i didn't close it with the commit.

**Comment by jonathon-love** [comment]
i think we're still waiting on a fix from @raviselker

**Comment by jonathon-love** [comment]
is "there are aliased co-efficients in the model" the best error message we can come up with? :/

**Comment by raviselker** [comment]
It's not something "we" came up with, it's the error message the R package gives. Not sure what's happening there, so also not sure what a better error message would be.
