### ISSUE TITLE
The condition has length > 1 ... bug in anovaRM and RMNP.

### ISSUE THREAD

**Issue by MattMcMullen** [jamovi/jmv#151]
I get this when I use anovaRM in R but not in jamovi, even after copying the syntax from jamovi. I believe it always appears when I create a plot, and is never there when there is no plot. 

But I also see this in anovaRMNP without any plot. 

The error looks like this: 

the condition has length > 1 and only the first element will be usedthe condition has length > 1 and only the first element will be used

repeated over and over in red. There seem to be more repetitions of it when there are more factors or more levels maybe. The plot and results appear to be correct despite the message.

**Comment by jonathon-love** [comment]
hi,

try updating to the latest jmvcore (0.8.5), and see if that fixes things for you.

with thanks

**Comment by MattMcMullen** [comment]
Yes, those error messages are gone now, thanks!
