### ISSUE TITLE
Feature request: confidence intervals for effect sizes

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#158]
I know this is too much to ask, but I was wondering if it will be possible to also include confidence intervals for effect sizes for the common tests in future versions of `jmv/jamovi`? 
So, basically, confidence intervals for: 

> Cohen's _d_, 
> Hedge's _g_,
> partial eta-squared, 
> omega-squared, 
> Pearson's _r_, 
> Spearman's _rho_ ,
> _phi_ coefficient,
> Cramer's _V_

This is in part inspired by reading _Understanding The New Statistics: Effect Sizes, Confidence Intervals, and Meta-Analysis_ by Cumming (2014) which emphasizes how effect sizes and their confidence intervals is what behavioral sciences should be focusing on.

Thanks!

**Comment by jonathon-love** [comment]
hi @IndrajeetPatil,

this sort of thing probably belongs in a module. the new statistics guys *do* plan to develop a jamovi module, so maybe keen an eye out for that.

cheers

jonathon

**Comment by IndrajeetPatil** [comment]
Okay, cool. Will do!

**Comment by IndrajeetPatil** [comment]
@jonathon-love and @raviselker:
On a related note, the 95% CIs are currently displayed only for Pearson's _r_, but not for other non-parametric correlations. Is this a bug or that's how it is supposed to be?

![image](https://user-images.githubusercontent.com/11330453/38525989-744b7d5c-3c22-11e8-84d0-e22b67d84de4.png)

**Comment by IndrajeetPatil** [comment]
@jonathon-love I think this will make a great module for `jamovi` to get the effect sizes and their confidence intervals:
https://github.com/doomlab/MOTE

**Comment by jonathon-love** [comment]
oh, we never responded to your april 10 post. yeah, that's the way it's supposed to be.

wrt MOTE jamovi module: yes! let us know if you need any help with it :)

jonathon
