### ISSUE TITLE
Adding n.unique argument to descriptives

### ISSUE THREAD

**Issue by BobMuenchen** [jamovi/jmv#166]
The Hmisc package has a very useful argument that is called n.unique. When the number of unique values that a variable contains is 10 or fewer, then Hmisc::describe will automatically add frequency tables to its output. I'm proposing that descriptives(mydata) would default to providing means, etc. for all numeric variables regardless of number of unique values, and provide frequency tables for all variables which are factors or which are numeric with 10 or fewer values.

**Comment by jonathon-love** [comment]
ah yup, that's a good idea.

our current approach is to provide frequency tables for factors. this works in the jamovi context, because the jamovi import function converts variables with less than 50 unique values to be factors (same behaviour as spss).

however, the R context is a bit different, and something like your described behaviour would be nice. let me give it some thought.

jonathon

**Comment by BobMuenchen** [comment]
Are you sure jamovi imports variables with fewer than 50 unique characters as factors? I just used the GUI to import some Likert-scale data. It imported with the triple-circle icon representing nominal, and when I ran descriptives, it gave me both the summary stats and frequency tables. That's good since social scientists would often get means & std dev's on such variables and they'd want frequency tables too.

Then I created a tiny data frame with a single factor and ran it through jmv syntax expecting the same result. But this time it refused to calculate the summary stats. 

> df
  x
1 1
2 2
3 3
4 4
5 5
> class(df$x)
[1] "factor"

> mean(df$x)
[1] NA

Warning message:
In mean.default(df$x) : argument is not numeric or logical: returning NA

> summary(df$x)
1 2 3 4 5 
1 1 1 1 1 

> descriptives(data=df, vars="x")

 DESCRIPTIVES

 Descriptives     
 ──────────────── 
              x   
 ──────────────── 
   N          5   
   Missing    0   
   Mean           
   Median         
   Minimum        
   Maximum        
 ──────────────── 

> descriptives(data=df, vars="x", freq = TRUE)

 DESCRIPTIVES

 Descriptives     
 ──────────────── 
              x   
 ──────────────── 
   N          5   
   Missing    0   
   Mean           
   Median         
   Minimum        
   Maximum        
 ──────────────── 


 FREQUENCIES

 Frequencies of x                                   
 ────────────────────────────────────────────────── 
   Levels    Counts    % of Total    Cumulative %   
 ────────────────────────────────────────────────── 
   1              1          20.0            20.0   
   2              1          20.0            40.0   
   3              1          20.0            60.0   
   4              1          20.0            80.0   
   5              1          20.0           100.0   
 ────────────────────────────────────────────────── 

Well heck, after all that you probably just meant to say "nominal" instead of "factor". This makes we wonder what is nominal? A new class of object?

**Comment by BobMuenchen** [comment]
I just ran into this issue again & was surprised at the output. For a simple example, here's the mtcars data. Getting frequency tables on some of the vars with a small number of values, like number of cylinders, would be nice. Rather than just ignoring the numeric vars with its current design, it puts out empty tables. I'm just passing that along in case that wasn't what you intended.

 ─────────────────── 

> table(mtcars$cyl)

 4  6  8 
11  7 14 

> mtcars %>% jmv::descriptives(freq = TRUE)

 DESCRIPTIVES

 Descriptives                                                                                          
 ───────────────────────────────────────────────────────────────────────────────────────────────────── 
              mpg     cyl     disp    hp      drat    wt      qsec    vs       am       gear    carb   
 ───────────────────────────────────────────────────────────────────────────────────────────────────── 
   N            32      32      32      32      32      32      32       32       32      32      32   
   Missing       0       0       0       0       0       0       0        0        0       0       0   
   Mean       20.1    6.19     231     147    3.60    3.22    17.8    0.438    0.406    3.69    2.81   
   Median     19.2    6.00     196     123    3.70    3.33    17.7     0.00     0.00    4.00    2.00   
   Minimum    10.4    4.00    71.1    52.0    2.76    1.51    14.5     0.00     0.00    3.00    1.00   
   Maximum    33.9    8.00     472     335    4.93    5.42    22.9     1.00     1.00    5.00    8.00   
 ───────────────────────────────────────────────────────────────────────────────────────────────────── 


 FREQUENCIES

 Frequencies of mpg <---The presence of these empty tables seemed odd
 ────────────────── 
  
 ────────────────── 
 ────────────────── 


 Frequencies of cyl 
 ────────────────── 
  
 ────────────────── 
 ────────────────── 


 Frequencies of disp 
 ─────────────────── 
  
 ─────────────────── 
 ─────────────────── 


 Frequencies of hp 
 ───────────────── 
  
 ───────────────── 
 ───────────────── 


 Frequencies of drat 
 ─────────────────── 
  
 ─────────────────── 
 ─────────────────── 


 Frequencies of wt 
 ───────────────── 
  
 ───────────────── 
 ───────────────── 


 Frequencies of qsec 
 ─────────────────── 
  
 ─────────────────── 
 ─────────────────── 


 Frequencies of vs 
 ───────────────── 
  
 ───────────────── 
 ───────────────── 


 Frequencies of am 
 ───────────────── 
  
 ───────────────── 
 ───────────────── 


 Frequencies of gear 
 ─────────────────── 
  
 ─────────────────── 
 ─────────────────── 


 Frequencies of carb 
 ─────────────────── 
  
 ─────────────────── 
 ───────────────────

**Comment by jonathon-love** [comment]
OK, i've fixed the empty table issue, but returning to the original suggestion:

> provide frequency tables for all variables which are factors or which are numeric with 10 or fewer values.

could you take a look at this @raviselker ?

the `.initFrequencyTables()` function does some slightly unusual things, so i'm reluctant to touch it myself.
