### ISSUE TITLE
Adding extreme values table to descriptives

### ISSUE THREAD

**Issue by BobMuenchen** [jamovi/jmv#168]
Whenever a student comes in asking how to interpret a 4- or 5-way interaction in ANOVA, the first thing I do is run SPSS' Explore procedure and ask for the Extreme Values table on their dependent variable. It simply shows the 5 largest and smallest values (and case number), and very likely one or two of those values is a huge data entry error. Fixing that usually removes the high-level interaction. Such a table would be a very helpful addition to jmv's descriptives.

![image](https://user-images.githubusercontent.com/3144156/38198717-eb44255c-365b-11e8-8794-a344608e7c6a.png)

**Comment by jonathon-love** [comment]
this is a good idea, what do you think @raviselker ?
