### ISSUE TITLE
Correcting p-values for Multiple Testing

### ISSUE THREAD

**Issue by BobMuenchen** [jamovi/jmv#170]
It would be very helpful to have the option to use the base p.adjust function to adjust p-values for the effects of multiple testing. The psych package's corr.test does this using adjust=holm by default, and R Commander (and its RcmdrMisc subset) prints both adjusted and non-adjusted by default in the rcorr.adjust function. It would make sense to offer this in any dialog box that makes it easy to crank out lots of tests, such as crosstabs, t-tests, mann-whitneys. This problem is the main reason we see rejected journal articles, usually for vast piles of t-tests.
(I hope this isn't a duplicate request. I thought I entered it before but can't find it; sorry if it is!)

**Comment by jonathon-love** [comment]
so a lot of our analyses provide p-corrections in the post-hoc tests, but are you meaning across all analyses? i.e. every time another p-value appears, it adjusts all the p-values visible in the results panel?

jonathon

**Comment by BobMuenchen** [comment]
Your existing procedures that do post-hoc testing are fine. I mean just those p-values that result from listing multiple variables in any single dialog box. Looking across an entire set of analyses (i.e. multiple dialog boxes from various menus) is is a good thing for researchers to keep in mind, but I think that would be too messy to include as a feature. 

I've attached my favorite paper on the effects of multiple testing. He uses a computer simulation to show that the probability of finding at least one significant correlation in a matrix generated from five variables (10 correlations) is 40% rather than the 5% that most users are expecting:
[Multiple Testing Analyzing Tables of Stat Tests.pdf](https://github.com/jamovi/jmv/files/1903758/Multiple.Testing.Analyzing.Tables.of.Stat.Tests.pdf)


Here are the dialog boxes that make it easy to crank out a set of analyses:

Correlation: number of variables in a single matrix
t-tests / Mann-Whitney: number of dependent variables or number of paired samples
One-way ANOVA (Non-parametric): number of dependent variables
Proportion Test (2 Outcomes): number of variables tested
Contingency Tables: unlike in SPSS, this doesn't accept more than one row/column variable at the moment, so this would be only the number of layers

**Comment by RenaudJA** [comment]
Hats off to the team for this amazing work!!
I fully agree with BobMuenchen's point. A multiple testing correction such as the one proposed in the corr.test package (with option to choose the adjustment method: fdr, holm, etc) would be very helpful since this constitues a common error in lots of papers++
A suggestion to consider for a future update of the Regression module/menu may be?
