### ISSUE TITLE
Feature Request: plotting options & presentation mode

### ISSUE THREAD

**Issue by patel011393** [jamovi/jmv#186]
Hi,

I've benefitted from using jamovi greatly over the past year and would like to suggest some additional features based on my experiences:

1. It would be nice if users could easily change the x-axis and y-axis limits on plots. My colleagues and collaborators frequently ask for this and I end up switching to R.

2. Ridgeline plots (formerly joy plots) would be great to include into the plotting options. https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html

They would help save space by condensing multiple density plots into one plot and enable easier comparison between distributions.

3. A presentation mode would be a cool and useful innovation in stats programs. If I want to show my analyses from my computer to someone sitting near me, I should be able to go into a "full screen mode" or something similar to focus on just the tables and plots we're working on. The zoom function works, but it's not the same.

**Comment by jonathon-love** [comment]
hey, great to hear (FYI, this is the jmv issues list, where as you probably want to post this in the [jamovi issues list](https://github.com/jamovi/jamovi/issues )

1. yup, we'll add plot editing soon.

2. so we do makes use of ggridges in our histograms in descriptives. is that what you want?

3. yeah, a presentation mode is a neat idea. i'll give it some thought.

cheers

jonathon
