### ISSUE TITLE
Changing "anova" to "ANOVA"

### ISSUE THREAD

**Issue by BobMuenchen** [jamovi/jmv#191]
I've been using the jmv package a lot and its conflict with stats::anova is confusing to students. In addition, car::Anova is very widely used. Please consider using all caps "ANOVA" to avoid those conflicts.

**Comment by jonathon-love** [comment]
yeah, probably a good idea ... it kinda mucks up our naming scheme is all.

**Comment by jonathon-love** [comment]
what do you think @raviselker ? we can provide a deprecation period.

**Comment by raviselker** [comment]
Yeah, you will always have name-clashes, but `stats::anova` is such a widely used function that this might be a problematic one.
