### ISSUE TITLE
log odds ratio for McNemar Test producing NaNs

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#194]
Here is a reproducible example:

``` r

# preparing data
dat <- data.frame(
  `1st survey` = c('Approve', 'Approve', 'Disapprove', 'Disapprove'),
  `2nd survey` = c('Approve', 'Disapprove', 'Approve', 'Disapprove'),
  `Counts` = c(794, 150, 86, 570),
  check.names = FALSE
)

# getting log odds ratio
jmv::contTablesPaired(
  data = dat,
  rows = '1st survey',
  cols = '2nd survey',
  counts = 'Counts',
  exact = TRUE
)
#> 
#>  PAIRED SAMPLES CONTINGENCY TABLES
#> 
#>  Contingency Tables                               
#>  ------------------------------------------------ 
#>    1st survey    Approve    Disapprove    Total   
#>  ------------------------------------------------ 
#>    Approve           794           150      944   
#>    Disapprove         86           570      656   
#>    Total             880           720     1600   
#>  ------------------------------------------------ 
#> 
#> 
#>  McNemar Test                                      
#>  ------------------------------------------------- 
#>                            Value    df    p        
#>  ------------------------------------------------- 
#>    <U+03C7>²                       17.4     1    < .001   
#>    Log odds ratio exact      NaN                   
#>    N                        1600                   
#>  -------------------------------------------------
```

Created on 2018-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by jonathon-love** [comment]
hi, sorry for the delay in getting to this. it's returning `NaN` because you don't have the `exact2x2` package installed. i've added an informative error message now.

thanks for reporting.

**Comment by IndrajeetPatil** [comment]
Thanks for fixing this. 

Any particular reason why `exact2x2` is in `Suggests`, and not `Imports`? 

From the perspective of writing a wrapper function in my package (`ggstatsplot`) around this function, it will be nice if `exact2x2` package is already downloaded when `jmv` is downloaded. It also doesn't look very heavy in terms of its dependencies.

**Comment by jonathon-love** [comment]
yeah, i just try and keep the number of dependencies at a minimum (which is pretty funny, because we have over a hundred)... the chances of any single jmv user wanting this particular statistic is quite low, so that's why i put it as a suggests.

but if you want to be able to reliably use this from `ggstatsplot`, put `exact2x2` as an import in `ggstatsplot`.
