### ISSUE TITLE
bayes factor error term for `ttestOneS`: different from JASP

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#195]
The `error (in %)` term for Bayes Factor seems to be different for `jamovi` as compared to `JASP`. Not sure which one is the correct one, but just wanted to point this out. The `BF` values are consistent across two softwares though.

**jmv**
``` r
jmv::ttestOneS(data = sleep, vars = "extra", bf = TRUE)
#> 
#>  ONE SAMPLE T-TEST
#> 
#>  One Sample T-Test                                                    
#>  -------------------------------------------------------------------- 
#>                               statistic    error %    df      p       
#>  -------------------------------------------------------------------- 
#>    extra    Student's t            3.41               19.0    0.003   
#>             Bayes factor10         14.5    3.77e-6                    
#>  --------------------------------------------------------------------
```

**JASP**
![image](https://user-images.githubusercontent.com/11330453/44375623-9e39d100-a4c2-11e8-8fd1-657d96b86ccc.png)

**Comment by jonathon-love** [comment]
hey,

bayes factors (in jamovi and jasp) aren't deterministic, so you'll get slightly different results each time.

cheers

**Comment by IndrajeetPatil** [comment]
I see. I was worried because those are orders of magnitude differences! But if that's to be expected, then no worries.

**Comment by jonathon-love** [comment]
wait, they're both 14.5, no?

**Comment by IndrajeetPatil** [comment]
No, I am talking about the Bayes factor **error** (in %) term.

**Comment by jonathon-love** [comment]
ah! yeah. i don't think that's a problem. in both cases it's a very precise estimate.

**Comment by IndrajeetPatil** [comment]
Gotcha! Thanks.
