### ISSUE TITLE
Truncation of output in RStudio Notebooks

### ISSUE THREAD

**Issue by BobMuenchen** [jamovi/jmv#197]
Using both descriptives and contTables, the output is truncated in RStudio's Notebook mode, though not in the console. To see this problem:

1. In RStudio, choose File> New File> R Notebook. That will give you the default notebook. 

2. Paste the following code in, and click the green "Run current chunk" arrow.

```{r}
library("tidyverse")
library("jmv")
mycars <- mtcars %>%
  mutate(
    cyl=factor(cyl),
    vs = factor(vs),
    am = factor(am),
    gear = factor(gear),
    carb = factor(carb)
  )

jmv::descriptives(mycars, freq = TRUE)
```

In that notebook window, you should see it truncate the output just as it gets to the frequency tables. 

In my program, I'm using lots of different packages which is what makes me think it has something to do with jmv output instead of being an RStudio problem. I downloaded the RStudio daily build on 9/4/18 to verify that it's still an issue with that version, and it is.

The Word doc that was generated via Pandoc shows all the output.

**Comment by jonathon-love** [comment]
righto. i'll take a look.

i'm not as on-top of these issues at the moment because RStudio flat-out refuses to run on my computer, all of a sudden. i've tried rolling back to older versions, etc. etc. but can't get anything to work.

(it does make me feel a bit better about when jamovi doesn't work on some obscure machine in arctic poland though)

with thanks

**Comment by raviselker** [comment]
Over here (RStudio 1.0.143) everythings seems to be working fine:
![screenshot from 2018-09-18 22-59-34](https://user-images.githubusercontent.com/4669197/45733717-9f7c1d80-bb96-11e8-9b84-fbdb8037359e.png)

**Comment by BobMuenchen** [comment]
It's working fine for me now too. I might have been using one of the RStudio daily builds when that happened.
