### ISSUE TITLE
Cramer's V is bias-corrected?

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#199]
I can't find this in the `jmv` documentation, so raising an issue here. 

Cramer's _V_ has a large bias for finite samples and there is a bias-correction method:
https://www.sciencedirect.com/science/article/pii/S1226319212001032?via%3Dihub

Is the _V_ produced `jmv` already corrected for this bias? Or is it uncorrected?

I know `rcompanion::cramerV()` (https://github.com/cran/rcompanion/blob/master/R/cramerV.r) has `bias.correct` argument that (I think) does this:
https://github.com/cran/rcompanion/blob/18338c3e4a9234b09f053ea549a209884a0ece74/R/cramerV.r#L66-L70
  
But it would be lovely if this is implemented in `jmv`, if it already isn't.

**Comment by jonathon-love** [comment]
we use `vcd` for cramer's v:

https://github.com/jamovi/jmv/blob/master/R/conttables.b.R#L227
https://www.rdocumentation.org/packages/vcd/versions/1.4-4/topics/assocstats

which doesn't mention anything about a correction, so i assume it's uncorrected.

**Comment by IndrajeetPatil** [comment]
I see. Maybe it will be worth it to also add this option and give a new (e.g., `cramer.bias.correct = TRUE`) argument to the function in future versions?

**Comment by jonathon-love** [comment]
oh yup, we can take a look.
