### ISSUE TITLE
`NEWS.md` for new releases?

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#202]
I wanted to request including a `NEWS.md` in future releases of `jmv` on `CRAN`. This makes it easy for downstream dependencies (like `ggstatsplot`) to decide whether they should be bumping `jmv` versions in the `DESCRIPTION` file based on what new features have been added in the recent release. 

Thanks.

**Comment by jonathon-love** [comment]
oh yup, that's not a bad idea. you can just look at the commit history too.

cheers
