### ISSUE TITLE
New version of psych breaks some things:

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#214]
from bill:

> I am in the process of trying to get psych up on CRAN.  I ran the devcheck and it reports a problem with the tests in jmv.
> 
> My current development version may be found at 
> 
>      install.pacakges("psych",repos= "https://personality-project.org/r", type="source”)
> 
> Could you look at it and let me know what you think the problem is?
> 
> Thanks.
> 
> Bill

follow-up:

> Thanks.
> 
> In addition, there is a bug (as yet not found) that I introduced into the FA function.  I will have a 1.8.10 version to put on my server as soon as I track this one down.
> 
> Bill

**Comment by jonathon-love** [comment]
> I tracked down my bug in fa  and the new release on my server is 1.8.10
> I have not tried it against jmv yet.  But will do so tomorrow.
> You might see if jmv works against the newest version. 
> 
> Bill

**Comment by raviselker** [comment]
Hmm, that repo doesn't seem to work over here...

**Comment by raviselker** [comment]
Tests appear to be working against the newest version. Hooray for unit tests :tada:

**Comment by revelle** [comment]
That is great.  thanks for checking.

**Comment by jonathon-love** [comment]
are we backwards compatible @raviselker, or do we need to add `>= 1.8.10` to the `psych` import?

**Comment by revelle** [comment]
the version that broke on JMV was a test version that was not released.  I think you are ok.

Thanks.



> On Oct 27, 2018, at 12:00 AM, Jonathon Love <notifications@github.com> wrote:
> 
> are we backwards compatible @raviselker, or do we need to add >= 1.8.10 to the psych import?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

William Revelle		           personality-project.org/revelle.html
Professor			                   personality-project.org
Department of Psychology         www.wcas.northwestern.edu/psych/
Northwestern University	           www.northwestern.edu/
Use R for psychology                 personality-project.org/r
It is 2 1/2  minutes to midnight	   www.thebulletin.org
