### ISSUE TITLE
`walrus` independent t-test isn't working

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#217]
I am working with the jamvoi `0.9.5.12` and robust independent t-test doesns't work.

It gives "there is no package called `reshape`" error.

![image](https://user-images.githubusercontent.com/11330453/50063926-7cccc580-01d4-11e9-9fa3-62e84167ff61.png)

**Comment by jonathon-love** [comment]
try updating ... or uninstalling and reinstalling.

cheers

**Comment by IndrajeetPatil** [comment]
Uninstalled and reinstalled the newer version `0.9.5.13`, but still the same issue.

![image](https://user-images.githubusercontent.com/11330453/50066712-6a0dbd00-01e3-11e9-9f2a-23bd31e22e17.png)

**Comment by jonathon-love** [comment]
i mean uninstall and reinstall walrus. what OS is this?

**Comment by IndrajeetPatil** [comment]
Ah, gotcha. Now it's working. I am on a Windows machine.

**Comment by jonathon-love** [comment]
yeah, i found that issue a while ago, and sometimes i don't bump the version number of a package when i make a fix, because then i have to go and build that package for all the OSes again.

so my laziness let you down here.
