### ISSUE TITLE
bugs data url incorrect?

### ISSUE THREAD

**Issue by IndrajeetPatil** [jamovi/jmv#220]
Is this URL correct? I don't see anything about bugs in this paper.
https://github.com/jamovi/jmv/blob/57226a0f8accf1bbb46a6f128a32e3c79583d917/R/data.R#L9

**Comment by jonathon-love** [comment]
> ... rated the frighteningness and disgustingness of 44 different insects. These ratings were used to select eight insects, two of which were in each of the four categories resulting from crossing high and low frighteningness with high and low disgustingness. The insects selected for the four categories are shown in Fig. 1.

Figure 1. doesn't seem to display in FF (not sure if it's an issue with FF or the pdf), which is a shame, because that is a great picture.
