### ISSUE TITLE
jmv repeated measures ancova

### ISSUE THREAD

**Issue by MilicaNinkovic** [jamovi/jmv#248]
Hello! 
I am trying to run the anovaRM function with 3 WS factors, one BS factor, and one covariate. However, the output does not contain any info about the covariate, and the results are exactly the same when I include the covariate as when I do not include it.

Here is the code (without emmeans and other functions, to keep it as simplest as possible) 
anovaRM(
  data = EA_wide,
  rm = list(
    list(
      label = 'Status',
      levels = c('Majority', 'Minority')),
    list(
      label = 'Parent',
      levels = c('Father', 'Mother')),
    list(
      label = 'min_Ethnicity',
      levels = c('Bosniak', 'Albanian', 'Roma'))),
  rmCells = list(
    list(
      measure = 'OV_O_B',
      cell = c('Majority', 'Father', 'Bosniak')),
    list(
      measure = 'OV_O_A',
      cell = c('Majority', 'Father', 'Albanian')),
    list(
      measure = 'OV_O_R',
      cell = c('Majority', 'Father', 'Roma')),
    list(
      measure = 'MV_M_B',
      cell = c('Majority', 'Mother', 'Bosniak')),
    list(
      measure = 'MV_M_A',
      cell = c('Majority', 'Mother', 'Albanian')),
    list(
      measure = 'MV_M_R',
      cell = c('Majority', 'Mother', 'Roma')),
    list(
      measure = 'MV_O_B',
      cell = c('Minority', 'Father', 'Bosniak')),
    list(
      measure = 'MV_O_A',
      cell = c('Minority', 'Father', 'Albanian')),
    list(
      measure = 'MV_O_R',
      cell = c('Minority', 'Father', 'Roma')),
    list(
      measure = 'OV_M_B',
      cell = c('Minority', 'Mother', 'Bosniak')),
    list(
      measure = 'OV_M_A',
      cell = c('Minority', 'Mother', 'Albanian')),
    list(
      measure = 'OV_M_R',
      cell = c('Minority', 'Mother', 'Roma'))),
  bs = Gender, 
  cov = ZEssentialism,
  effectSize = 'partEta',
  rmTerms = list(
    'Status', 'Parent', 'min_Ethnicity'),
  bsTerms = 'Gender', 'ZEssentialism'
)

**Comment by jonathon-love** [comment]
hi,

can you provide the data set (or a data set i can use), so i can run this?

with thanks

**Comment by MilicaNinkovic** [comment]
Hi,

I eventually solved the problem by copying the code from Syntax mode in Jamovi to the R console :)
thanks anyway

**Comment by jonathon-love** [comment]
great :)

**Comment by jonathon-love** [comment]
yeah, the jmv RM ANOVA syntax isn't exactly a thing of beauty ... i've been meaning to tidy it up a bit.
