### ISSUE TITLE
loglinear model blocks not working

### ISSUE THREAD

**Issue by victor-moreno** [jamovi/jmv#292]
Hi,
I cannot add terms to a second block in loglinear models. The arrows or dragging don't work in mac nor cloud.
The linear and logistic regression pages work as expected.
I think it may be related to the javascript code but I don't know that language
Victor

**Comment by jonathon-love** [comment]
hi victor,

i've just had a quick look, and this appears to be working. are you perhaps trying to add items to a subsequent block, that already exist in a previous block?

<img width="583" alt="Screen Shot 2021-02-05 at 09 06 56" src="https://user-images.githubusercontent.com/3240247/106961380-97d26900-6791-11eb-9daf-28f235db36cd.png">

**Comment by victor-moreno** [comment]
Hi, 
Yes, it works if the term is not in previous block! This was not intuitive to me.

Since the first block adds a saturated model, I tried to add terms for a simpler model in the second block, but I couldn't add anything. I wanted to compare the saturated model with a less complicated model (backwards). I see now that to do that I have to first remove interaction terms.

I see that in linear regression, since only main effects are added in first block, the second can naturally have interactions.

Sorry about that

Victor

**Comment by jonathon-love** [comment]
yeah, damo and i discussed ways we could make this clearer. damo's having a think about it.

cheers
