### ISSUE TITLE
Contingency tables: Variable names with spaces cause bar plots to fail

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#303]
do you have time to look at this @victor-moreno ? otherwise one of us can have a look.

cheers

jonathon

**Comment by victor-moreno** [comment]
Hi, sorry but not until May 22nd, I have a grant deadline. I could take care then if that is ok

**Comment by jonathon-love** [comment]
no worries. one of us will probably take a look before then. i don't imagine it will be a difficult fix.

with thanks

**Comment by jonathon-love** [comment]
oh, i had a bit of a nibble on this, but decided to leave it to you. do you have time, or should i have another go at it?

with thanks

**Comment by jonathon-love** [comment]
oh, i think ravi fixed this
