### ISSUE TITLE
CRAN-version: Missing packages / dependencies

### ISSUE THREAD

**Issue by sjentsch** [jamovi/jmv#314]
When trying to run jmv::ANOVA in R, there are error messages because of missing dependencies:
data.table
readxl
carData
abind

**Comment by jonathon-love** [comment]
yeah, i don't think this has anything to do with us. we list `car` as an import, and it's someone/something else's responsibility to ensure `car`s dependencies get installed.

**Comment by sjentsch** [comment]
Oh, I see. Should I register an issue there?

**Comment by jonathon-love** [comment]
i think you'll find if you nuke your library and install `jmv` from scratch, everything will work.

so i don't think this will be reproducible ... and may have come about through any number of circumstances.

**Comment by sjentsch** [comment]
I see. Thanks!
