### ISSUE TITLE
Binomial Test: Add confidence interval UI

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#32]
hey @dropmann 

could you add confidence interval UI options to binomial.src.js ?

the options are already present in binomial.a.yaml

with thanks

**Comment by dropmann** [comment]
where should i put them? under a heading?

**Comment by jonathon-love** [comment]
yeah, i guess. Additional statistics?

**Comment by dropmann** [comment]
@jonathon, this has been added to the ui already

**Comment by jonathon-love** [comment]
implemented.
