### ISSUE TITLE
RM ANOVA UI: removing factors doesn't always work

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#41]
try removing Gender from the Between subjects factors of the following. (sometimes it works, suggesting it's a race condition)

[rm.omv.zip](https://github.com/jamovi/Rjamovi/files/553256/rm.omv.zip)

**Comment by dropmann** [comment]
I think this might be fixed with the last update. Could you check? i can't get it to happen.

**Comment by jonathon-love** [comment]
Fixed!
