### ISSUE TITLE
PropTestN: Add proportion UI

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#54]

**Comment by jonathon-love** [comment]
actually, this might be better. the left hand column is initialized to the levels, and the right hand column is initialized with the value 1.

![screen shot 2016-12-02 at 12 11 38](https://cloud.githubusercontent.com/assets/3240247/20819844/2bda7a08-b88b-11e6-8161-b8a7bd3a4f94.png)

**Comment by dropmann** [comment]
@jonathon-love, do i not put the radio buttons in anymore? I can't quite remember our final thoughts on this layout.

**Comment by raviselker** [comment]
I assume you can close this one
