### ISSUE TITLE
ANOVA UI: Removing factors does not cascade correctly

### ISSUE THREAD

**Issue by jonathon-love** [jamovi/jmv#55]
in this case, i had the fixed factors `Gender` and `Region`, i then assigned these to the plot, then i removed `Gender`. as can be seen, `Gender` remains assigned to `Separate lines`

<img width="570" alt="screen shot 2016-12-02 at 18 01 09" src="https://cloud.githubusercontent.com/assets/3240247/20825625/83368386-b8b9-11e6-8bc8-46b377e41d47.png">

**Comment by dropmann** [comment]
@jonathon-love, this seems to work fine for me. Could you try again to see if my latest commits fixed this in passing?

**Comment by jonathon-love** [comment]
fixed!
