### ISSUE TITLE
RM ANOVA: Default name `RM Factor 1` does not show up in RM terms

### ISSUE THREAD

**Issue by raviselker** [jamovi/jmv#57]
If I use the default name `RM Factor 1` for the first term, it will not show up in the RM terms:
![screenshot from 2016-12-19 11-28-22](https://cloud.githubusercontent.com/assets/4669197/21309413/96536dbc-c5de-11e6-86b4-3d53796c55ad.png)

If I subsequently try to define them manually it will show `RM Factor 2` twice:
![screenshot from 2016-12-19 11-31-11](https://cloud.githubusercontent.com/assets/4669197/21309439/b8b38234-c5de-11e6-9061-5da47eb602a2.png)

**Comment by dropmann** [comment]
this should be fixed with my latest commit

**Comment by raviselker** [comment]
I can still make it do weird stuff (I pulled your latest commit):
![screenshot from 2016-12-28 16-36-59](https://cloud.githubusercontent.com/assets/4669197/21525191/f397c5ce-cd1b-11e6-99ac-1773732e8063.png)

Way to reproduce it:
1. go to RM ANOVA and add another RM Factor
2. go to model builder and drag both RM factors from the left box to the right box
