### ISSUE TITLE
RM ANOVA UI: scrollbar covers labels rm cells

### ISSUE THREAD

**Issue by raviselker** [jamovi/jmv#63]
![screenshot from 2017-01-05 15-33-05](https://cloud.githubusercontent.com/assets/4669197/21688691/1df38616-d36e-11e6-88c5-8c050856518c.png)

**Comment by raviselker** [comment]
This only happens when the cells are empty, if you drag and drop a variable it is moves the labels to the left of the scrollbar.

**Comment by dropmann** [comment]
this is fixed!
